<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdqXUS9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdqXUS9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYdqXUS9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYdqXUS9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYdqXUS9\App_KernelProdContainer([
    'container.build_hash' => 'YdqXUS9',
    'container.build_id' => 'bb4dc96b',
    'container.build_time' => 1616415690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdqXUS9');
