<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqBBiKc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqBBiKc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRqBBiKc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRqBBiKc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRqBBiKc\App_KernelDevDebugContainer([
    'container.build_hash' => 'RqBBiKc',
    'container.build_id' => 'ca8ee660',
    'container.build_time' => 1616415743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqBBiKc');
