<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGYBnVW7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGYBnVW7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGYBnVW7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGYBnVW7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGYBnVW7\App_KernelDevDebugContainer([
    'container.build_hash' => 'GYBnVW7',
    'container.build_id' => '78954278',
    'container.build_time' => 1616779450,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGYBnVW7');
