<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \App\Entity\Transaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'codeTransaction', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'frais', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'dateTransaction', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_etat', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_systeme', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_user_depot', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_user_retrait', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'utilisateurAP', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'compteAP'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'codeTransaction', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'frais', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'dateTransaction', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_etat', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_systeme', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_user_depot', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'part_user_retrait', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'utilisateurAP', '' . "\0" . 'App\\Entity\\Transaction' . "\0" . 'compteAP'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant(int $montant): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeTransaction(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeTransaction', []);

        return parent::getCodeTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeTransaction(string $codeTransaction): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeTransaction', [$codeTransaction]);

        return parent::setCodeTransaction($codeTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrais(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrais', []);

        return parent::getFrais();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrais(int $frais): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrais', [$frais]);

        return parent::setFrais($frais);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTransaction(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTransaction', []);

        return parent::getDateTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTransaction(\DateTimeInterface $dateTransaction): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTransaction', [$dateTransaction]);

        return parent::setDateTransaction($dateTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartEtat(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartEtat', []);

        return parent::getPartEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartEtat(?float $part_etat): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartEtat', [$part_etat]);

        return parent::setPartEtat($part_etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartSysteme(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartSysteme', []);

        return parent::getPartSysteme();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartSysteme(?float $part_systeme): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartSysteme', [$part_systeme]);

        return parent::setPartSysteme($part_systeme);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartUserDepot(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartUserDepot', []);

        return parent::getPartUserDepot();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartUserDepot(?float $part_user_depot): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartUserDepot', [$part_user_depot]);

        return parent::setPartUserDepot($part_user_depot);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartUserRetrait(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartUserRetrait', []);

        return parent::getPartUserRetrait();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartUserRetrait(?float $part_user_retrait): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartUserRetrait', [$part_user_retrait]);

        return parent::setPartUserRetrait($part_user_retrait);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateurAP(): ?\App\Entity\AdminSystem
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateurAP', []);

        return parent::getUtilisateurAP();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateurAP(?\App\Entity\AdminSystem $utilisateurAP): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateurAP', [$utilisateurAP]);

        return parent::setUtilisateurAP($utilisateurAP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteAP(): ?\App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteAP', []);

        return parent::getCompteAP();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteAP(?\App\Entity\CompteAgencePartenaire $compteAP): \App\Entity\Transaction
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteAP', [$compteAP]);

        return parent::setCompteAP($compteAP);
    }

}
