<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CompteAgencePartenaire extends \App\Entity\CompteAgencePartenaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'numeroCompte', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'solde', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'agencePartenaireAssociee', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'transactions', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'depots'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'numeroCompte', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'solde', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'agencePartenaireAssociee', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'transactions', '' . "\0" . 'App\\Entity\\CompteAgencePartenaire' . "\0" . 'depots'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CompteAgencePartenaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCompte(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCompte', []);

        return parent::getNumeroCompte();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCompte(string $numeroCompte): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCompte', [$numeroCompte]);

        return parent::setNumeroCompte($numeroCompte);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolde(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolde', []);

        return parent::getSolde();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolde(int $solde): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolde', [$solde]);

        return parent::setSolde($solde);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(bool $statut): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencePartenaireAssociee(): ?\App\Entity\AgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencePartenaireAssociee', []);

        return parent::getAgencePartenaireAssociee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencePartenaireAssociee(\App\Entity\AgencePartenaire $agencePartenaireAssociee): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencePartenaireAssociee', [$agencePartenaireAssociee]);

        return parent::setAgencePartenaireAssociee($agencePartenaireAssociee);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactions', []);

        return parent::getTransactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addTransaction(\App\Entity\Transaction $transaction): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransaction', [$transaction]);

        return parent::addTransaction($transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTransaction(\App\Entity\Transaction $transaction): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTransaction', [$transaction]);

        return parent::removeTransaction($transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepots(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepots', []);

        return parent::getDepots();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepot(\App\Entity\Depot $depot): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepot', [$depot]);

        return parent::addDepot($depot);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepot(\App\Entity\Depot $depot): \App\Entity\CompteAgencePartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepot', [$depot]);

        return parent::removeDepot($depot);
    }

}
