<?php

namespace ContainerYdqXUS9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSystemRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AdminSystemRepository' shared autowired service.
     *
     * @return \App\Repository\AdminSystemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AdminSystemRepository'] = new \App\Repository\AdminSystemRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
