<?php

namespace ContainerYdqXUS9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgencePartenaireRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AgencePartenaireRepository' shared autowired service.
     *
     * @return \App\Repository\AgencePartenaireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AgencePartenaireRepository'] = new \App\Repository\AgencePartenaireRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
